title: "Visual Proofs"
email: solida@students.uni-marburg.de
timezone: UTC
baseurl: ""
url: "https://visualproofs.github.io"
logo: 'assets/images/logo.png'
favicon: 'assets/images/circle.ico'
author: Solida Neziri
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed


# Authors
authors:
  solida:
    name: Solida Neziri
    display_name: Solida Neziri
    avatar: 'assets/images/sl.JPEG'
    email: solida@students.uni-marburg.de
    description: "You are currently witnessing a CS Student trying to navigate through her B.Thesis."
  georges:
    name: Georges Hattab
    display_name: Georges Hattab
    email: solida@students.uni-marburg.de
    description: ""
  moritz:
    name: Moritz Weckbecker
    display_name: Moritz Weckbecker
    email: weckbeckerm@rki.de
    description: "A funny placeholder quote about me"
# Social
social:
  instagram: https://www.instagram.com/solidaneziri/

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives